budget_app/urls.py

from django.urls import path
from . import views

app_name = 'budget_app'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('transactions/', views.transactions, name = 'transactions'),
    path('transaction/<int:transaction_id>/', views.transaction, name='transaction'),
    path('new_entry/<int:transaction_id>/', views.new_entry , name='new_entry'),
    path('bar_chart/', views.bar_chart, name='bar_chart'),
    path('delete/<int:entry_id>/',views.delete, name='delete'),

]

budget_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('budget_app.urls'))
]

budget_app/models.py
from django.db import models

# Create your models here.

class Transaction(models.Model):
    #Transaction user wants to record( after make any changes to this* must run makemigrations cmd)
    TransactionType = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        #Return a string reprensentation of model (method)
        return str(self.TransactionType)
    

class Entry(models.Model):
    transactions = models.ForeignKey('Transaction', on_delete=models.CASCADE)
    merchant = models.CharField(max_length=200)
    description = models.TextField()
    transaction_amount = models.FloatField(max_length=10)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return str(self.merchant)


budget_app/forms.py
from django import forms

from . models import Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['merchant', 'description', 'transaction_amount']
        labels = {
            'merchant': 'Merchant',
            'description': 'Description',
            'transaction_amount': 'Transaction Amount'
        }
        widgets = {
            'description': forms.Textarea(attrs={'cols': 80})}


budget_app/views.py
from django.shortcuts import render
from . models import Transaction , Entry
from django.http import HttpResponseRedirect
from django.urls import reverse

from . forms import EntryForm
import plotly.express as px
import pandas as pd



# Create your views here.

def index (request):
    """Home page"""
    return render(request, 'budget_app/index.html')

def transactions(request):
    """Showing transactions"""
    transactions = Transaction.objects.order_by('date_added')
    context = {'transactions': transactions}
    return render(request,'budget_app/transactions.html', context)

def transaction(request, transaction_id):
    """Showing single transactions and all entries"""
    transaction = Transaction.objects.get(id=transaction_id)
    entries = transaction.entry_set.order_by('-date_added')
    context = {'transaction': transaction, 'entries': entries}
    return render(request,'budget_app/transaction.html', context)



def new_entry(request, transaction_id):
    """Add new entry for a particular transaction"""
    transaction = Transaction.objects.get(id=transaction_id)

    if request.method != 'POST':
       #no data submitted (creates blank form) 
       form = EntryForm()
    else:
        #POST Data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.transactions = transaction
            new_entry.save()
            return HttpResponseRedirect(reverse('budget_app:transaction', args=[transaction_id]))
    context = {'transaction': transaction, 'form': form}
    return render(request, 'budget_app/new_entry.html', context)

def bar_chart(request):
    """Show/design the bar chart"""
    transactions =  Transaction.objects.all()
    transaction_amount = [(transaction.TransactionType, sum(entry.transaction_amount for entry in transaction.entry_set.all())) for transaction in transactions]
    df = pd.DataFrame(transaction_amount, columns=['Transaction Type', 'Transaction Amount'])
    fig = px.bar(df, x='Transaction Type', y='Transaction Amount', color = 'Transaction Type')
    fig.update_yaxes(tickformat='d', dtick=10)
    chart_html = fig.to_html()
    context = {'chart_html': chart_html}
    return render(request, 'budget_app/bar_chart.html', context)

def delete(request, entry_id):
    """Delete specific topic"""
    Entry.objects.filter(id=entry_id).delete()
    return HttpResponseRedirect(reverse('budget_app:transactions'))

budget_app/templates/budget_app/bar_chart.html
{% extends "budget_app/base.html" %}
{% block content %}
<p><h1>Income / Spending</h1>
    <hr class="my-6"></p>
<p>{{ chart_html | safe }}</p>
{% endblock content %}

budget_app/templates/budget_app/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Budget App</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">

</head>

<body>
    <nav class="navbar navbar-dark bg-primary">
      
        <a class="navbar-brand" href="{% url 'budget_app:index'%}">Budget App</a>
        <a class="nav-item text-white" href="{% url 'budget_app:transactions'%}">Transactions</a>
        <a class="nav-item text-white" href="{% url 'budget_app:bar_chart'%}">Track Your Spending</a>
       
    
	  </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

budget_app/templates/budget_app/index.html
{% extends "budget_app/base.html" %}

{% block page_header %}
    <div class="jumbotron mt-4">
        <h1>Pythonic Purse</h1>
        <p class="lead">A python budget application</p>
        <hr class="my-6">
        <p>Intelligent Budgeting. Python-Powered</p>
      </div>
{% endblock page_header %}

{% block content %}
<h2>This Budget App will help you achieve the goals you're working toward. Hopefully it will give you an action plan of where your money is going.</h2>

{% endblock content %}

budget_app/templates/budget_app/new_entry.html
{% extends "budget_app/base.html" %}
{% load bootstrap4 %}


{% block content %}
    <p><h2>Add a new entry:</h2></p>
    <hr class="my-6">
    <p><a href="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a></p>
        <form action="{% url 'budget_app:new_entry' transaction.id %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}  
            <button type="submit" class="btn btn-primary"> Add Entry</button>
        </form>

{% endblock content %}

budget_app/templates/budget_app/transaction.html
{% extends "budget_app/base.html" %}

{% block content %}

<p><h1>{{ transaction }}</h1>
  <hr class="my-6"></p>

  <p><a href="{% url 'budget_app:new_entry' transaction.id %}">add new entry</a></p>


 
    
    <table class="table table-hover">
        <thead class="table-dark">
          <tr>
            <th scope="col">Merchant</th>
            <th scope="col">Description</th>
            <th scope="col">Amount</th>
            <th scope="col">Date Added</th>
            <th scope="col">Delete Entry</th>
          </tr>
        </thead>
        <tbody>
            {% for entry in transaction.entry_set.all %}
            <tr class="table-light">
                <td>{{ entry.merchant }}</td>
                <td>{{ entry.description }}</td>
                <td>{{ entry.transaction_amount }}</td>
                <td>{{ entry.date_added|date:'M d, Y h:i' }}</td>
                <td><a href="{% url 'budget_app:delete' entry.id %}">delete entry</a></td>
              </tr>
            {% empty %}
              <tr>
                <li>There are no entries for this transaction yet.</li>
              </tr>
            {% endfor %}
        </tbody>
    </table>
        




{% endblock content %}

budget_app/templates/budget_app/transactions.html
{% extends "budget_app/base.html" %}

{% block content %}

<p><h1>Transactions</h1>
    <hr class="my-6"></p>


<ul>
    {% for transaction in transactions %}
        <li>
            <a href="{% url 'budget_app:transaction' transaction.id %}">{{ transaction }}</a>
        </li>
    {% empty %}
        <li>No transactions have been added yet.</li>
    {% endfor %}

</ul>



{% endblock content %}